version: '2'
services:
  mssql:
    build: ./MSSQL
    ports:
     - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'yourStrong(!)Password'
      MSSQL_PID: Developer
    volumes:
     - ./MSSQL/output/:/usr/src/output
     - ./MSSQL/sql/:/usr/src/sql
     - mssqldata:/var/opt/mssql
volumes:
  mssqldata:
    driver: "local"